name: Update inventory JSON.GZ

permissions:
  contents: write

on:
  push:
    paths:
      - "data/inventory.json"
      - "tools/regen_inventory_json_gz.py"
      - ".github/workflows/update-inventory-gz.yml"
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Regenerate compressed file
        run: python tools/regen_inventory_json_gz.py

      - name: Validate gzip content
        run: |
          python - <<'PYCODE'
          import gzip, json, sys, os
          path = "data/inventory.json.gz"
          if not os.path.exists(path) or os.path.getsize(path) < 10:
              print("❌ ERROR: archivo vacío o no encontrado.")
              sys.exit(1)
          try:
              d = gzip.open(path, "rb").read()
              json.loads(d.decode("utf-8"))
              print("✅ Validación JSON OK — tamaño:", len(d), "bytes")
          except Exception as e:
              print("❌ ERROR: contenido no válido ->", e)
              sys.exit(1)
          PYCODE

      - name: Commit and push updated gz
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/inventory.json.gz
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: auto-regenerated inventory.json.gz (validated)"
            git push
          fi
